import { sanitizeHtml, sanitizeFileName } from './sanitize';

/**
 * Export diff as HTML file
 */
export function exportAsHtml(original: string, modified: string, title?: string): void {
  try {
    const originalObj = JSON.parse(original);
    const modifiedObj = JSON.parse(modified);
    const safeTitle = sanitizeHtml(title || 'JSON Diff');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${safeTitle}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f5f5;
            padding: 20px;
        }
        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header {
            background: #2563eb;
            color: white;
            padding: 20px;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 8px;
        }
        .meta {
            font-size: 14px;
            opacity: 0.9;
        }
        .content {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1px;
            background: #e5e7eb;
        }
        .panel {
            background: white;
            padding: 20px;
        }
        .panel-header {
            font-weight: 600;
            font-size: 14px;
            text-transform: uppercase;
            color: #6b7280;
            margin-bottom: 16px;
            padding-bottom: 8px;
            border-bottom: 2px solid #e5e7eb;
        }
        pre {
            background: #f9fafb;
            padding: 16px;
            border-radius: 6px;
            overflow-x: auto;
            font-family: 'Monaco', 'Menlo', 'Courier New', monospace;
            font-size: 13px;
            line-height: 1.6;
        }
        .added {
            background: #d1fae5;
            color: #065f46;
        }
        .removed {
            background: #fee2e2;
            color: #991b1b;
        }
        .footer {
            padding: 16px 20px;
            background: #f9fafb;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>${title || 'JSON Diff Comparison'}</h1>
            <div class="meta">Generated on ${new Date().toLocaleString()}</div>
        </div>
        <div class="content">
            <div class="panel">
                <div class="panel-header">Original JSON</div>
                <pre>${escapeHtml(JSON.stringify(originalObj, null, 2))}</pre>
            </div>
            <div class="panel">
                <div class="panel-header">Modified JSON</div>
                <pre>${escapeHtml(JSON.stringify(modifiedObj, null, 2))}</pre>
            </div>
        </div>
        <div class="footer">
            Generated by JSON Differ | ${window.location.origin}
        </div>
    </div>
</body>
</html>`;

    downloadFile(html, `${title || 'json-diff'}.html`, 'text/html');
  } catch (error) {
    throw new Error('Cannot export invalid JSON as HTML');
  }
}

/**
 * Export diff as Markdown file
 */
export function exportAsMarkdown(original: string, modified: string, title?: string): void {
  try {
    const originalObj = JSON.parse(original);
    const modifiedObj = JSON.parse(modified);

    const markdown = `# ${title || 'JSON Diff Comparison'}

**Generated:** ${new Date().toLocaleString()}

---

## Original JSON

\`\`\`json
${JSON.stringify(originalObj, null, 2)}
\`\`\`

---

## Modified JSON

\`\`\`json
${JSON.stringify(modifiedObj, null, 2)}
\`\`\`

---

## Summary

- **Original Size:** ${getSize(original)}
- **Modified Size:** ${getSize(modified)}
- **Timestamp:** ${new Date().toISOString()}

---

*Generated by [JSON Differ](${window.location.origin})*
`;

    downloadFile(markdown, `${title || 'json-diff'}.md`, 'text/markdown');
  } catch (error) {
    throw new Error('Cannot export invalid JSON as Markdown');
  }
}

/**
 * Export diff comparison as plain text
 */
export function exportAsText(original: string, modified: string, title?: string): void {
  const text = `${title || 'JSON DIFF COMPARISON'}
${'='.repeat(60)}

Generated: ${new Date().toLocaleString()}

ORIGINAL JSON:
${'-'.repeat(60)}
${original}

MODIFIED JSON:
${'-'.repeat(60)}
${modified}

${'='.repeat(60)}
End of comparison
`;

  downloadFile(text, `${title || 'json-diff'}.txt`, 'text/plain');
}

/**
 * Helper: Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

/**
 * Helper: Get formatted size
 */
function getSize(jsonString: string): string {
  const bytes = new Blob([jsonString]).size;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

/**
 * Helper: Trigger file download
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = sanitizeFileName(filename);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
